/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import utility.BDutility;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import forms.StudentRegistration;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 *
 * @author Tesla Laptops
 */
public class AdminWindow extends javax.swing.JFrame {
    
    private JPopupMenu popupMenu,popupEdit;
    private JMenuItem miSecA, miSecB, miSecC, miSecD,miEditA,miEditB,miEditC,miEditD;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminWindow.class.getName());

    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
        editComponents();
        wireEditPopup();
          BDutility.setimage(this, "images/admin-panel.jpg", 745, 506);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        btnView = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnaddstudent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnviewnotif = new javax.swing.JButton();
        btnsendnotif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bdmexit = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN PANEL");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        btnView.setBackground(new java.awt.Color(38, 50, 56));
        btnView.setForeground(new java.awt.Color(200, 220, 230));
        btnView.setText("View Time Table");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(38, 50, 56));
        btnEdit.setForeground(new java.awt.Color(200, 220, 230));
        btnEdit.setText("Edit Time Table");

        btnaddstudent.setBackground(new java.awt.Color(38, 50, 56));
        btnaddstudent.setForeground(new java.awt.Color(200, 220, 230));
        btnaddstudent.setText("Add Student");
        btnaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstudentActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(38, 50, 56));
        jButton1.setForeground(new java.awt.Color(200, 220, 230));
        jButton1.setText("Add Faculty");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnviewnotif.setBackground(new java.awt.Color(38, 50, 56));
        btnviewnotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notification2.png"))); // NOI18N
        btnviewnotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewnotifActionPerformed(evt);
            }
        });

        btnsendnotif.setBackground(new java.awt.Color(38, 50, 56));
        btnsendnotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/149-1498854_paper-plane-paper-plane-icon-png-transparent-png (2).png"))); // NOI18N
        btnsendnotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendnotifActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO ADMIN PANEL");

        bdmexit.setBackground(new java.awt.Color(255, 0, 0));
        bdmexit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdmexit.setForeground(new java.awt.Color(255, 255, 255));
        bdmexit.setText("X");
        bdmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdmexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnView)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnviewnotif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsendnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnsendnotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewnotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnView)
                .addGap(36, 36, 36)
                .addComponent(btnEdit)
                .addGap(37, 37, 37)
                .addComponent(btnaddstudent)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       private void wireEditPopup() {
        popupEdit = new JPopupMenu();
        miEditA = new JMenuItem("SecA");
        miEditB = new JMenuItem("SecB");
        miEditC = new JMenuItem("SecC");
        miEditD = new JMenuItem("SecD");

        popupEdit.add(miEditA);
        popupEdit.add(miEditB);
        popupEdit.add(miEditC);
        popupEdit.add(miEditD);

        btnEdit.addActionListener(e ->
                popupEdit.show(btnEdit, 0, btnEdit.getHeight()));

        miEditA.addActionListener(e -> openTimetableEdit("A"));
        miEditB.addActionListener(e -> openTimetableEdit("B"));
        miEditC.addActionListener(e -> openTimetableEdit("C"));
        miEditD.addActionListener(e -> openTimetableEdit("D"));
    }


    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstudentActionPerformed
        BDutility.openForm(StudentRegistration.class.getSimpleName(), new StudentRegistration());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddstudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BDutility.openForm(FacultyRegistration.class.getSimpleName(), new FacultyRegistration());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnviewnotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewnotifActionPerformed
    // Fetch all requests (any role) from DB
 java.util.List<String> notes = dao.NotificationViewer.getNotifications("admin");
    if (notes.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No new notifications.");
        return;
    }
    JTextArea area = new JTextArea();
    area.setEditable(false);
    for (String line : notes) {
        area.append(line + "\n\n");
    }
    JScrollPane scroll = new JScrollPane(area);
    scroll.setPreferredSize(new Dimension(400, 300));
    JOptionPane.showMessageDialog(
        this,
        scroll,
        "Notifications",
        JOptionPane.INFORMATION_MESSAGE
    );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewnotifActionPerformed

    private void btnsendnotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendnotifActionPerformed
        // 1) Prompt Admin for message text:
    String message = JOptionPane.showInputDialog(
        this,
        "Enter notification message:",
        "Send Notification",
        JOptionPane.PLAIN_MESSAGE
    );
    if (message == null || message.trim().isEmpty()) {
        return; // Admin cancelled or left blank
    }

// 2) Ask Admin who should receive it (Student, Faculty, or All)
    String[] options = { "Student", "Faculty", "All" };
    String recipient = (String) JOptionPane.showInputDialog(
        this,
        "Send to:",
        "Recipient Type",
        JOptionPane.QUESTION_MESSAGE,
        null,
        options,
        options[0]
    );
if (recipient == null) {
    return; // Cancelled
}

// 3) Actually insert into DB via DAO
boolean ok = dao.NotificationSender.sendNotification(
    message,
    recipient,      // e.g. “Student” or “Faculty” or “All”
    "Admin"         // Hard-coded sender name
);
if (ok) {
    JOptionPane.showMessageDialog(this, "Notification sent successfully.");
} else {
    JOptionPane.showMessageDialog(this, "Error sending notification.", 
                                  "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnsendnotifActionPerformed

    private void bdmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdmexitActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_bdmexitActionPerformed
    private void editComponents() {
        // **Do NOT create a new JButton here.**
        // Instead, use the one that initComponents() already made for us:
        //
        //    btnView = new JButton("View");
        //    btnView.setBounds(20, 30, 80, 30);
        //    add(btnView);
        //
        // Remove both of those lines and simply attach the popup to the existing btnView.

        // 1) Create popup menu and items:
        popupMenu = new JPopupMenu();
        miSecA = new JMenuItem("Sec A");
        miSecB = new JMenuItem("Sec B");
        miSecC = new JMenuItem("Sec C");
        miSecD = new JMenuItem("Sec D");

        popupMenu.add(miSecA);
        popupMenu.add(miSecB);
        popupMenu.add(miSecC);
        popupMenu.add(miSecD);

        // 2) Show popup when clicking the already-existing btnView:
        btnView.addActionListener(e -> {
            // Show popup directly beneath btnView
            popupMenu.show(btnView, 0, btnView.getHeight());
        });

        // 3) Handle each menu item’s action:
        miSecA.addActionListener(e -> openTimetable("A"));
        miSecB.addActionListener(e -> openTimetable("B"));
        miSecC.addActionListener(e -> openTimetable("C"));
        miSecD.addActionListener(e -> openTimetable("D"));

    }

    private void openTimetable(String sectionCode) {
    Timetable tf = new Timetable(sectionCode);
    tf.setVisible(true);
    }
    
    private void openTimetableEdit(String sectionCode) {
    TimetableFrameEdit tf2 = new TimetableFrameEdit(sectionCode);
    tf2.setVisible(true);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdmexit;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnaddstudent;
    private javax.swing.JButton btnsendnotif;
    private javax.swing.JButton btnviewnotif;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}
