/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dao.NotificationSender;
import dao.NotificationViewer;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import utility.BDutility;

/**
 *
 * @author Syeds
 */
public class FacultyDashboard extends javax.swing.JFrame {
    private JPopupMenu popupMenu;
    private JMenuItem miSecA, miSecB, miSecC, miSecD;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyDashboard.class.getName());

    /**
     * Creates new form FacultyDashboard
     */
    private final String loggedInEmail;
    public FacultyDashboard(String email) {
        this.loggedInEmail = email;
        initComponents();
        BDutility.setimage(this, "images/admin-panel.jpg", 745, 506);
    }

    public String getLoggedInEmail() {
    return loggedInEmail;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bdmexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnnotify = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        viewnotifications = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(712, 371));
        setMinimumSize(new java.awt.Dimension(712, 371));
        setUndecorated(true);

        bdmexit.setBackground(new java.awt.Color(255, 0, 0));
        bdmexit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdmexit.setForeground(new java.awt.Color(255, 255, 255));
        bdmexit.setText("X");
        bdmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdmexitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Faculty Dashboard");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notify Admin/Students");

        btnnotify.setBackground(new java.awt.Color(38, 50, 56));
        btnnotify.setForeground(new java.awt.Color(200, 220, 230));
        btnnotify.setText("Notify");
        btnnotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotifyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View Notifications");

        viewnotifications.setBackground(new java.awt.Color(38, 50, 56));
        viewnotifications.setForeground(new java.awt.Color(200, 220, 230));
        viewnotifications.setText("View Notifcations");
        viewnotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewnotificationsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View Time Table");

        btnView.setBackground(new java.awt.Color(38, 50, 56));
        btnView.setForeground(new java.awt.Color(200, 220, 230));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnnotify)
                                    .addComponent(btnView)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(viewnotifications)))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(btnView))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnnotify))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewnotifications, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 105, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bdmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdmexitActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_bdmexitActionPerformed

    private void btnnotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotifyActionPerformed

        // 1) Prompt for the message
String message = JOptionPane.showInputDialog(
    this,
    "Enter notification message:",
    "Send Notification",
    JOptionPane.PLAIN_MESSAGE
);
if (message == null || message.trim().isEmpty()) {
    return;  // cancelled or empty
}

// 2) Prompt for recipient type (Student, Admin, or All)
String[] options = { "Student", "Admin", "All" };
String recipient = (String) JOptionPane.showInputDialog(
    this,
    "Send to:",
    "Recipient Type",
    JOptionPane.QUESTION_MESSAGE,
    null,
    options,
    options[0]
);
if (recipient == null) {
    return; // user cancelled
}

// 3) Insert into DB via DAO, using the logged-in faculty’s email as sender
boolean ok = NotificationSender.sendNotification(
    message,
    recipient.toLowerCase(),
    this.loggedInEmail
);

if (ok) {
    JOptionPane.showMessageDialog(
        this,
        "Notification sent successfully to " + recipient + ".",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
    );
} else {
    JOptionPane.showMessageDialog(
        this,
        "Error sending notification.",
        "Error",
        JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_btnnotifyActionPerformed

    private void viewnotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewnotificationsActionPerformed
        // TODO add your handling code here:
         java.util.List<String> notifs = NotificationViewer.getNotifications("faculty");
    if (notifs.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No notifications for you.");
        return;
    }
    JTextArea area = new JTextArea(String.join("\n\n", notifs));
    area.setEditable(false);
    JScrollPane scroll = new JScrollPane(area);
    scroll.setPreferredSize(new Dimension(400, 300));
    JOptionPane.showMessageDialog(
        this,
        scroll,
        "Notifications for Faculty",
        JOptionPane.INFORMATION_MESSAGE
    );
    
    }//GEN-LAST:event_viewnotificationsActionPerformed
    
    private void openTimetable(String sectionCode) {
    Timetable tf = new Timetable(sectionCode);
    tf.setVisible(true);
    }
    
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
                popupMenu = new JPopupMenu();
        miSecA = new JMenuItem("Sec A");
        miSecB = new JMenuItem("Sec B");
        miSecC = new JMenuItem("Sec C");
        miSecD = new JMenuItem("Sec D");

        popupMenu.add(miSecA);
        popupMenu.add(miSecB);
        popupMenu.add(miSecC);
        popupMenu.add(miSecD);

        // 2) Show popup when clicking the already-existing btnView:
        btnView.addActionListener(e -> {
            // Show popup directly beneath btnView
            popupMenu.show(btnView, 0, btnView.getHeight());
        });

        // 3) Handle each menu item’s action:
        miSecA.addActionListener(e -> openTimetable("A"));
        miSecB.addActionListener(e -> openTimetable("B"));
        miSecC.addActionListener(e -> openTimetable("C"));
        miSecD.addActionListener(e -> openTimetable("D"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdmexit;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnnotify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton viewnotifications;
    // End of variables declaration//GEN-END:variables
}
