/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Syeds
 */

import dao.NotificationViewer;
import java.awt.Dimension;
import utility.BDutility;
import javax.swing.*;

public class StudentDashboard extends javax.swing.JFrame {
    private JPopupMenu popupMenu;
    private JMenuItem miSecA, miSecB, miSecC, miSecD;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboard.class.getName());
    
    /**
     * Creates new form StudentDashboard
     */
    
    private String loggedInEmail;
    public StudentDashboard(String email) {
        this.loggedInEmail = email;
        initComponents();
        BDutility.setimage(this, "images/admin-panel.jpg", 745, 506);
    }
    
    public String getLoggedInEmail() {
    return loggedInEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnrequest = new javax.swing.JButton();
        bdmexit = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        viewnotifications = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Timetable ");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Dashboard");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Request To Change Timetable");

        btnrequest.setBackground(new java.awt.Color(38, 50, 56));
        btnrequest.setForeground(new java.awt.Color(200, 220, 230));
        btnrequest.setText("Request");
        btnrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestActionPerformed(evt);
            }
        });

        bdmexit.setBackground(new java.awt.Color(255, 0, 0));
        bdmexit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bdmexit.setForeground(new java.awt.Color(255, 255, 255));
        bdmexit.setText("X");
        bdmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdmexitActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(38, 50, 56));
        btnView.setForeground(new java.awt.Color(200, 220, 230));
        btnView.setText("View Time Table");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View Notifications");

        viewnotifications.setBackground(new java.awt.Color(38, 50, 56));
        viewnotifications.setForeground(new java.awt.Color(200, 220, 230));
        viewnotifications.setText("View Notifcations");
        viewnotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewnotificationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewnotifications))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addComponent(bdmexit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrequest))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewnotifications, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestActionPerformed
        PollDialog dlg = new PollDialog(this, true);
    dlg.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrequestActionPerformed

    private void bdmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdmexitActionPerformed
    this.dispose();
    new Login().setVisible(true);
    }//GEN-LAST:event_bdmexitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
                popupMenu = new JPopupMenu();
        miSecA = new JMenuItem("Sec A");
        miSecB = new JMenuItem("Sec B");
        miSecC = new JMenuItem("Sec C");
        miSecD = new JMenuItem("Sec D");

        popupMenu.add(miSecA);
        popupMenu.add(miSecB);
        popupMenu.add(miSecC);
        popupMenu.add(miSecD);

        // 2) Show popup when clicking the already-existing btnView:
        btnView.addActionListener(e -> {
            // Show popup directly beneath btnView
            popupMenu.show(btnView, 0, btnView.getHeight());
        });

        // 3) Handle each menu item’s action:
        miSecA.addActionListener(e -> openTimetable("A"));
        miSecB.addActionListener(e -> openTimetable("B"));
        miSecC.addActionListener(e -> openTimetable("C"));
        miSecD.addActionListener(e -> openTimetable("D"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void viewnotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewnotificationsActionPerformed

        // TODO add your handling code here:
         java.util.List<String> notifs = NotificationViewer.getNotifications("student");
    if (notifs.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No notifications for you.");
        return;
    }
    JTextArea area = new JTextArea(String.join("\n\n", notifs));
    area.setEditable(false);
    JScrollPane scroll = new JScrollPane(area);
    scroll.setPreferredSize(new Dimension(400, 300));
    JOptionPane.showMessageDialog(
        this,
        scroll,
        "Notifications for Student",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_viewnotificationsActionPerformed
    
    private void openTimetable(String sectionCode) {
    Timetable tf = new Timetable(sectionCode);
    tf.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String email=null;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentDashboard(email).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdmexit;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnrequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton viewnotifications;
    // End of variables declaration//GEN-END:variables
}